#test1_change
---
# this file assumes Automation Hub is the default source
collections:
- name: infoblox.nios_modules
  version: 1.0.0
# dig command pulled from here
- name: community.general
  version: 2.0.0
  source: https://galaxy.ansible.com
- name: ansible.netcommon
  version: 1.5.0
- name: ansible.windows
  version: 1.4.0
  source: https://galaxy.ansible.com
- name: community.windows
  version: 1.3.0
  source: https://galaxy.ansible.com