---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Create in memory inventory with created VM
    add_host:
      name: "{{ linux_hostname }}"
      ansible_host: "{{ linux_ip_address }}"
      groups: rhel_server
  
- hosts: rhel_server
  gather_facts: no
  tasks:
    - name: Get the hostname
      debug:
        var: "{{ inventory_hostname }}" 
    - name: Ping the server
      ping:
    # - name: Create the user and associated directory
    #   include_role:
    #     name: linux_create_user

    # - name: Configure /etc/resolve.conf
    #   include_role:
    #     name: configure_resolve_conf

    # - name: Register and Subscribe to RHEL
    #   include_role:
    #     name: register_rhel_subscription

    # - name: Patch the linux machine
    #   include_role:
    #     name: linux_patching