---
- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Gather vmware host facts
      community.vmware.vmware_host_facts:
        esxi_hostname: "192.168.2.22"
        validate_cert: false
      register: host_facts
      delegate_to: localhost

    - name: debug the message
      debug:
        msg: "{{ host_facts.stdout }}"