---
# tasks file for create_linux_vm
- name: Provision RHEL machine
  vmware_guest:
    hostname: "aap1.iisl.lab"
    username: "{{vm_username}}"
    password: "{{vm_password}}"
    guest_id: "{{vm_guest_id}}"
    folder: "{{vm_folder}}"
    template: "{{vm_template}}"
    validate_certs: no
    name: "{{vm_name}}"
    state: "{{vm_state}}"
    cluster: "{{vm_cluster}}"
    datastore: "{{vm_datastore}}"
    datacenter: "{{vm_datacenter}}"
    networks:
     - name: "{{vm_network}}"
       type: dynamic
       domain: "{{vm_domain_name}}"
       dns_servers:
         - 192.168.2.201
    customization:
       hostname: "{{vm_name}}"
       dns_servers:
         - 192.168.2.201
       domain: "{{vm_domain_name}}"
       state: started
    wait_for_ip_address: yes
    wait_for_customization: yes
  register: rhel_vm

- debug:
    var: rhel_vm
