---
---
# tasks file for create_linux_vm
- name: Provision RHEL machine
  vmware_guest:
    folder: "RHEL-Automation"
    template: "rhel7"
    validate_certs: no
    name: "{{vm_name}}"
    state: poweredon
    cluster: "RHEL-Automation"
    datastore: "Demo-Datastore01"
    datacenter: "Plainview"
    networks:
     - name: "RHEL-Automation - vLAN 102"
       type: dhcp
       domain: "{{vm_name}}.iisl.lab"
       dns_servers:
         - 192.168.2.201
    customization:
       hostname: '"{{vm_name}}".iisl.lab'
       dns_servers:
         - 192.168.2.201
       domain: "dns.iisl.lab"
       state: started
    wait_for_ip_address: yes
    wait_for_customization: yes
  register: rhel_vm

- debug:
    var: rhel_vm