---
# tasks file for create_directory_for_ad_user
- name: Create directories for AD user
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
   - /home/{{linux_user}}/ansible
   - /home/{{linux_user}}/temp_files
